// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// OP
List OP(std::vector<double> data, double penalty);
RcppExport SEXP _svpChange_OP(SEXP dataSEXP, SEXP penaltySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type penalty(penaltySEXP);
    rcpp_result_gen = Rcpp::wrap(OP(data, penalty));
    return rcpp_result_gen;
END_RCPP
}
// PELT
List PELT(std::vector<double> data, double penalty);
RcppExport SEXP _svpChange_PELT(SEXP dataSEXP, SEXP penaltySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type penalty(penaltySEXP);
    rcpp_result_gen = Rcpp::wrap(PELT(data, penalty));
    return rcpp_result_gen;
END_RCPP
}
// SVP
List SVP(std::vector<double> data, double gamma, std::string test, bool prune_if_unvalid);
RcppExport SEXP _svpChange_SVP(SEXP dataSEXP, SEXP gammaSEXP, SEXP testSEXP, SEXP prune_if_unvalidSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< std::string >::type test(testSEXP);
    Rcpp::traits::input_parameter< bool >::type prune_if_unvalid(prune_if_unvalidSEXP);
    rcpp_result_gen = Rcpp::wrap(SVP(data, gamma, test, prune_if_unvalid));
    return rcpp_result_gen;
END_RCPP
}
// svp0
List svp0(std::vector<double> data, double gamma, Function test, bool prune_if_unvalid, bool prune_if_PELT);
RcppExport SEXP _svpChange_svp0(SEXP dataSEXP, SEXP gammaSEXP, SEXP testSEXP, SEXP prune_if_unvalidSEXP, SEXP prune_if_PELTSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< Function >::type test(testSEXP);
    Rcpp::traits::input_parameter< bool >::type prune_if_unvalid(prune_if_unvalidSEXP);
    Rcpp::traits::input_parameter< bool >::type prune_if_PELT(prune_if_PELTSEXP);
    rcpp_result_gen = Rcpp::wrap(svp0(data, gamma, test, prune_if_unvalid, prune_if_PELT));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_svpChange_OP", (DL_FUNC) &_svpChange_OP, 2},
    {"_svpChange_PELT", (DL_FUNC) &_svpChange_PELT, 2},
    {"_svpChange_SVP", (DL_FUNC) &_svpChange_SVP, 4},
    {"_svpChange_svp0", (DL_FUNC) &_svpChange_svp0, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_svpChange(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
