// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// svp
List svp(Rcpp::NumericVector data, double gamma, Function test, bool all_full_validity);
RcppExport SEXP _svpChange_svp(SEXP dataSEXP, SEXP gammaSEXP, SEXP testSEXP, SEXP all_full_validitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< Function >::type test(testSEXP);
    Rcpp::traits::input_parameter< bool >::type all_full_validity(all_full_validitySEXP);
    rcpp_result_gen = Rcpp::wrap(svp(data, gamma, test, all_full_validity));
    return rcpp_result_gen;
END_RCPP
}
// test0
int test0();
RcppExport SEXP _svpChange_test0() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test0());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_svpChange_svp", (DL_FUNC) &_svpChange_svp, 4},
    {"_svpChange_test0", (DL_FUNC) &_svpChange_test0, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_svpChange(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
