# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Optimal Partitioning Algorithm
#'
#' @title Optimal Partitioning Algorithm
#' @description This function implements the OP algorithm of a given vector `data` with a given penalty term.
#' It finds the optimal change points that minimize a penalized cost using dynamic programming.
#'
#' @param data A numeric vector representing the data to segment.
#' @param penalty A double value representing the penalty term for adding a new segment.
#'
#' @return A list with (1) the `\code{changepoints}` elements, (2) a vector `\code{nb}` saving the number of non-pruned elements at each iteration, (3) a vector `\code{lastIndexSet}` containing the non-pruned indices at the end of the algo and (4) a vector `\code{costQ}` saving the optimal cost at each time step. The elements `\code{nb}` and `\code{lastIndexSet}` are set to NULL. They are included for consistency with other algorithms that prune the number of indices to be tracked over time.
#'
#' @examples
#' n <- 1000
#' data <- rep(c(0, 1, -0.5, 0), each = n) + rnorm(4 * n)
#' penalty <- 2 * log(length(data))
#' OPres <- OP(data, penalty)
#' OPres$changepoints
#'
#' @export
OP <- function(data, penalty) {
    .Call(`_svpChange_OP`, data, penalty)
}

#' Optimal Partitioning algorithm using PELT
#'
#' @title Optimal Partitioning using PELT
#' @description This function implements the OP algorithm using PELT of a given vector `data` with a given penalty term.
#' It finds the optimal changepoints that minimize the cost function using dynamic programming.
#'
#' @param data A numeric vector representing the data to segment.
#' @param penalty A double value representing the penalty term for adding a new segment.
#'
#' @return A list with
#' (1) the changepoint elements (each last index of each segment in \code{changepoints}),
#' (2) a vector \code{nb} saving the number of non-pruned elements at each iteration,
#' (3) a vector \code{lastIndexSet} containing the non-pruned indices at the end of the algorithm,
#' (4) a vector \code{costQ} saving the optimal cost at each time step.
#'
#' @examples
#' n <- 1000
#' data <- rep(c(0, 5, 2.5, 7), each = n) + rnorm(4 * n)
#' penalty <- 2 * log(length(data))
#' resPELT <- PELT(data, penalty)
#'
#' @export
PELT <- function(data, penalty) {
    .Call(`_svpChange_PELT`, data, penalty)
}

#' Smallest Valid Partitioning with Validation and Pruning using Rcpp
#'
#' @title Smallest Valid Partitioning with Validation and Pruning
#' @description This function implements a dynamic programming approach to segment a univariate signal into the smallest number of valid segments, according to a user-defined validation function. Each segment must pass a validity test (e.g., based on variance, range, etc.). The algorithm minimizes a quadratic cost subject to this constraint.
#'
#' @param data A numeric vector representing the univariate signal to be segmented.
#' @param gamma A numeric value used as a threshold in the validation function and as a penalty for each segment.
#' @param test A function of the form `function(data, gamma)` returning TRUE if the segment is valid. Default is `valid_OP`.
#' @param all_full_validity Logical. If TRUE (default), the algorithm applies *segment-wise validation*:
#' at each time step, it tests whether the candidate segment \code{data[(s+1):t]} is valid using the
#' user-defined function \code{test}. If the segment fails the test, the candidate \code{s} is removed
#' (pruned) from the set of possible change points. This accelerates computation by avoiding invalid
#' segment extensions. If FALSE, the algorithm skips this validation and considers all candidate
#' segments without checking their validity (which can be faster but may return invalid segments).
#'
#' @return A list with the following components:
#' \describe{
#'   \item{changepoints}{Integer vector indicating the ending index of each segment (i.e., positions of change points).}
#'   \item{nb}{Integer vector of length \code{length(data)}. At each position \code{t}, it records the number of candidates tested.}
#'   \item{costQ}{Numeric vector of length \code{length(data)}. Quadratic cost value at each time step.}
#'   \item{R}{A matrix of dimension \code{(length(data)+1) x 3} containing, for each time step :
#'     \describe{
#'       \item{Q}{cumulative cost}
#'       \item{K}{number of segments}
#'       \item{s}{the last change point (where the last segment starts)}
#'     }
#'   }
#' }
#'
#' @export
svp <- function(data, gamma, test, all_full_validity = TRUE) {
    .Call(`_svpChange_svp`, data, gamma, test, all_full_validity)
}

#' Test function returning 3
#'
#' This is a simple example of an exported C++ function
#' made available to R.
#'
#' @return An integer equal to 3.
#' @examples
#' test0()
#' @export
test0 <- function() {
    .Call(`_svpChange_test0`)
}

